name: drought
channels:
  - conda-forge
  - base
  - bioconda
  - R
dependencies:
  - r-base=4.3
  - r-tidyverse=2.0
  - r-rmarkdown=2.25
  - r-maps=3.4
  #- r-showtext
  - wget
  - snakemake=7.32.4
  - graphviz=8.1
  - coreutils=9.4